master:
  dateSource:
    url: jdbc:mysql://127.0.0.1:3306/jkapp_1630042506706026497?serverTimezone=GMT%2B8&useSSL=false&characterEncoding=UTF-8
    username: 
    password: 
    driver-class-name: com.mysql.cj.jdbc.Driver
second:
  dateSource:
    url: jdbc:mysql://127.0.0.1:3306/sxrtu?serverTimezone=GMT%2B8&useSSL=false&characterEncoding=UTF-8
    username: 
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
third:
  dateSource:
    jdbcUrl: jdbc:mysql://127.0.0.1:3306/demo?serverTimezone=GMT%2B8&useSSL=false&characterEncoding=UTF-8
    username:
    password: 
    driver-class-name: com.mysql.cj.jdbc.Driver
weChat:
  merchantId: 
  privateKeyPath: E:\\??\\privateKey\\apiclient_key.pem
  merchantSerialNumber:
  apiV3key:
  supplyAppId: 
  supplySecret:
  jiangshanAppId:
  jiangshanSecret: 

info:
  app:
    name: 智数江山
  version: v1.0.0
spring:
  main:
    allow-circular-references: true  #允许循环引用spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  profiles:
    pathmatch:
      matching-strategy: ant_path_matcher
    active: local
  application:
    name: open-demo
  jackson:
    date-format: com.fasterxml.jackson.databind.util.ISO8601DateFormat
  http:
    encoding:
      charset: UTF-8
      force: true
  datasource:
    username:
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/hikang_camera
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initialSize: 5
      maxActive: 20
#  h2:
#    console:
#      enabled: true
swagger:
  enabled: true


mybatis:
  mapper-locations: classpath:mapper/*/*.xml  #对应mapper映射xml文件所在路径
  type-aliases-package: com.example.jiangshan.entity  #对应实体类路径
logging:
  level:
    com.open.demov2.domain: debug

OPEN_URL: https://api2.hik-cloud.com
CLIENT_ID: 
CLIENT_SECRET: 
server:
  servlet:
    encoding:
      charset: UTF-8
