master:
  dateSource:
    url: jdbc:mysql://27.151.6.66:3306/jkapp_1630042506706026497?serverTimezone=GMT%2B8&useSSL=false&characterEncoding=UTF-8
    username: root
    password: ZScn8888888.
    driver-class-name: com.mysql.cj.jdbc.Driver
second:
  dateSource:
    url: jdbc:mysql://121.204.146.133:3306/sxrtu?serverTimezone=GMT%2B8&useSSL=false&characterEncoding=UTF-8
    username: root
    password: Xmsx123!@#
    driver-class-name: com.mysql.cj.jdbc.Driver
third:
  dateSource:
    jdbcUrl: jdbc:mysql://10.19.161.5:3306/demo?serverTimezone=GMT%2B8&useSSL=false&characterEncoding=UTF-8
    username: root
    password: Hik12345+
    driver-class-name: com.mysql.cj.jdbc.Driver
supply:
  dateSource:
    url: jdbc:mysql://27.151.6.66:3306/supplybiz?serverTimezone=GMT%2B8&useSSL=false&characterEncoding=UTF-8
    username: root
    password: ZScn8888888.
    driver-class-name: com.mysql.cj.jdbc.Driver
weChat:
  merchantId: 1636296954
  privateKeyPath: E:\\??\\privateKey\\apiclient_key.pem
  merchantSerialNumber: 2DBF0F8C1DDFF43780020628E81049536094D197
  apiV3key: sd15as1d56as1d56a156d156ad156as1
  supplyAppId: wxed05c9e3b45e9aa8
  supplySecret: 84f030f9ec70f2ee48f0176b7ade3f45
  jiangshanAppId: wx7e87828783de8ffc
  jiangshanSecret: ae9441b5ae49cc5be028bff858e90db8

info:
  app:
    name: 智数江山
  version: v1.0.0
spring:
  main:
    allow-circular-references: true  #允许循环引用spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  profiles:
    pathmatch:
      matching-strategy: ant_path_matcher
    active: local
  application:
    name: open-demo
  jackson:
    date-format: com.fasterxml.jackson.databind.util.ISO8601DateFormat
  http:
    encoding:
      charset: UTF-8
      force: true
  datasource:
    username: root
    password: ZScn8888888.
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://27.151.6.66:3306/hikang_camera?serverTimezone=GMT%2B8&useSSL=false&characterEncoding=UTF-8
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initialSize: 5
      maxActive: 20
#  h2:
#    console:
#      enabled: true
swagger:
  enabled: true


mybatis:
  mapper-locations: classpath:mapper/*/*.xml  #对应mapper映射xml文件所在路径
  type-aliases-package: com.example.jiangshan.entity  #对应实体类路径
logging:
  level:
    com.open.demov2.domain: debug

OPEN_URL: https://api2.hik-cloud.com
CLIENT_ID: 0fc2fa594ba143a8939f59fe088c54eb
CLIENT_SECRET: 4ebee99d9a2d42218dfa4c4e75cf3f3e
server:
  servlet:
    encoding:
      charset: UTF-8
