package com.example.jiangshan.open.domain;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import com.example.jiangshan.open.domain.entity.AccessPermissionGroup;

@Mapper
public interface AccessPermissionGroupMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table access_permission_group
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String permissionGroupId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table access_permission_group
     *
     * @mbg.generated
     */
    int insertSelective(AccessPermissionGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table access_permission_group
     *
     * @mbg.generated
     */
    AccessPermissionGroup selectByPrimaryKey(String permissionGroupId);

    List<AccessPermissionGroup> listPermissionGroups();

    int batchInsert(@Param("accessPermissionGroups") List<AccessPermissionGroup> accessPermissionGroups);
}