package com.example.jiangshan.open.domain;

import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import com.example.jiangshan.open.domain.entity.Group;

@Mapper
public interface GroupMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String groupId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group
     *
     * @mbg.generated
     */
    int insertSelective(Group record);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group
     *
     * @mbg.generated
     */
    Group selectByPrimaryKey(String groupId);

    Group selectByGroupNo(@Param("groupNo") String groupNo);

    int insert(Group record);

    List<Group> listGroups();

    int batchInsert(@Param("groups") List<Group> groups);
}
