package com.example.jiangshan.open.domain;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import com.example.jiangshan.open.domain.entity.DevicePermissionGroupRel;
import com.example.jiangshan.open.domain.entity.PersonPermissionGroupRel;

@Mapper
public interface PersonPermissionGroupRelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table person_permission_group_rel
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table person_permission_group_rel
     *
     * @mbg.generated
     */
    int insertSelective(PersonPermissionGroupRel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table person_permission_group_rel
     *
     * @mbg.generated
     */
    PersonPermissionGroupRel selectByPrimaryKey(String id);

    List<PersonPermissionGroupRel> listPermissionGroupPersons(@Param("groupId") String groupId);

    void batchInsert(@Param("personPermissionGroupRels")List<PersonPermissionGroupRel> personPermissionGroupRels);

    List<DevicePermissionGroupRel> listPermissionGroupPersonsByNo(@Param("groupId")String groupId, @Param("employeeNo")String employeeNo);
}