package com.example.jiangshan.open.domain;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import com.example.jiangshan.open.domain.entity.PersonCard;

@Mapper
public interface PersonCardMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table person_card
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table person_card
     *
     * @mbg.generated
     */
    int insertSelective(PersonCard record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table person_card
     *
     * @mbg.generated
     */
    PersonCard selectByPrimaryKey(String id);

    List<PersonCard> listByEmployeeNo(@Param("employeeNo") String employeeNo);

    void batchAddCards(@Param("personCards") List<PersonCard> personCards);
}