package com.example.jiangshan.open.domain.entity;

import java.util.Date;

import lombok.Data;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table device
 *
 * @mbg.generated do_not_delete_during_merge
 */
@Data
public class Device {

    private String deviceId;
    private String deviceSerial;
    private String deviceName;
    private String deviceModel;
    private String deviceStatus;
    private String validateCode;
    private String groupId;
    private Date createTime;

    public static final class aBuilder {
        private String deviceId;
        private String deviceSerial;
        private String deviceName;
        private String deviceModel;
        private String deviceStatus;
        private String validateCode;
        private String groupId;
        private Date createTime;

        private aBuilder() {
        }

        public static aBuilder aDevice() {
            return new aBuilder();
        }

        public aBuilder setDeviceId(String deviceId) {
            this.deviceId = deviceId;
            return this;
        }

        public aBuilder setDeviceSerial(String deviceSerial) {
            this.deviceSerial = deviceSerial;
            return this;
        }

        public aBuilder setDeviceName(String deviceName) {
            this.deviceName = deviceName;
            return this;
        }

        public aBuilder setDeviceModel(String deviceModel) {
            this.deviceModel = deviceModel;
            return this;
        }

        public aBuilder setDeviceStatus(String deviceStatus) {
            this.deviceStatus = deviceStatus;
            return this;
        }

        public aBuilder setValidateCode(String validateCode) {
            this.validateCode = validateCode;
            return this;
        }

        public aBuilder setGroupId(String groupId) {
            this.groupId = groupId;
            return this;
        }

        public aBuilder setCreateTime(Date createTime) {
            this.createTime = createTime;
            return this;
        }

        public Device build() {
            Device device = new Device();
            device.setDeviceId(deviceId);
            device.setDeviceSerial(deviceSerial);
            device.setDeviceName(deviceName);
            device.setDeviceModel(deviceModel);
            device.setDeviceStatus(deviceStatus);
            device.setValidateCode(validateCode);
            device.setGroupId(groupId);
            device.setCreateTime(createTime);
            return device;
        }
    }
}