package com.example.jiangshan.open.domain.entity;

import lombok.AllArgsConstructor;
import lombok.NoArgsConstructor;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table person_permission_group_rel
 *
 * @mbg.generated do_not_delete_during_merge
 */
@AllArgsConstructor
@NoArgsConstructor
public class PersonPermissionGroupRel {
    /**
     * 关联ID(id)
     */
    private String id;

    /**
     * 权限组ID(permission_group_id)
     */
    private String permissionGroupId;

    /**
     * 人员ID(employee_no)
     */
    private String employeeNo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column person_permission_group_rel.id
     *
     * @return the value of person_permission_group_rel.id
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column person_permission_group_rel.id
     *
     * @param id the value for person_permission_group_rel.id
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column person_permission_group_rel.permission_group_id
     *
     * @return the value of person_permission_group_rel.permission_group_id
     *
     * @mbg.generated
     */
    public String getPermissionGroupId() {
        return permissionGroupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column person_permission_group_rel.permission_group_id
     *
     * @param permissionGroupId the value for person_permission_group_rel.permission_group_id
     *
     * @mbg.generated
     */
    public void setPermissionGroupId(String permissionGroupId) {
        this.permissionGroupId = permissionGroupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column person_permission_group_rel.employee_no
     *
     * @return the value of person_permission_group_rel.employee_no
     *
     * @mbg.generated
     */
    public String getEmployeeNo() {
        return employeeNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column person_permission_group_rel.employee_no
     *
     * @param employeeNo the value for person_permission_group_rel.employee_no
     *
     * @mbg.generated
     */
    public void setEmployeeNo(String employeeNo) {
        this.employeeNo = employeeNo;
    }
}