package com.example.jiangshan.entity;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table access_permission_group
 *
 * @mbg.generated do_not_delete_during_merge
 */
@Data
@AllArgsConstructor
@NoArgsConstructor
public class AccessPermissionGroup {

    private String id;
    private String hikPermissionGroupId;
    private String permissionGroupName;
}