package com.example.jiangshan.entity;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table group
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class Group {
    /**
     */
    private String groupId;

    /**
     * 组编号(group_no)
     */
    private String groupNo;

    /**
     */
    private String groupName;

    /**
     */
    private String parentId;

    /**
     */
    private String path;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column group.group_id
     *
     * @return the value of group.group_id
     *
     * @mbg.generated
     */
    public String getGroupId() {
        return groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column group.group_id
     *
     * @param groupId the value for group.group_id
     *
     * @mbg.generated
     */
    public void setGroupId(String groupId) {
        this.groupId = groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column group.group_no
     *
     * @return the value of group.group_no
     *
     * @mbg.generated
     */
    public String getGroupNo() {
        return groupNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column group.group_no
     *
     * @param groupNo the value for group.group_no
     *
     * @mbg.generated
     */
    public void setGroupNo(String groupNo) {
        this.groupNo = groupNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column group.group_name
     *
     * @return the value of group.group_name
     *
     * @mbg.generated
     */
    public String getGroupName() {
        return groupName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column group.group_name
     *
     * @param groupName the value for group.group_name
     *
     * @mbg.generated
     */
    public void setGroupName(String groupName) {
        this.groupName = groupName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column group.parent_id
     *
     * @return the value of group.parent_id
     *
     * @mbg.generated
     */
    public String getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column group.parent_id
     *
     * @param parentId the value for group.parent_id
     *
     * @mbg.generated
     */
    public void setParentId(String parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column group.path
     *
     * @return the value of group.path
     *
     * @mbg.generated
     */
    public String getPath() {
        return path;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column group.path
     *
     * @param path the value for group.path
     *
     * @mbg.generated
     */
    public void setPath(String path) {
        this.path = path;
    }

    public static final class aBuilder {
        private String groupId;
        private String groupNo;
        private String groupName;
        private String parentId;
        private String path;

        private aBuilder() {
        }

        public static aBuilder aGroup() {
            return new aBuilder();
        }

        public aBuilder setGroupId(String groupId) {
            this.groupId = groupId;
            return this;
        }

        public aBuilder setGroupNo(String groupNo) {
            this.groupNo = groupNo;
            return this;
        }

        public aBuilder setGroupName(String groupName) {
            this.groupName = groupName;
            return this;
        }

        public aBuilder setParentId(String parentId) {
            this.parentId = parentId;
            return this;
        }

        public aBuilder setPath(String path) {
            this.path = path;
            return this;
        }

        public Group build() {
            Group group = new Group();
            group.setGroupId(groupId);
            group.setGroupNo(groupNo);
            group.setGroupName(groupName);
            group.setParentId(parentId);
            group.setPath(path);
            return group;
        }
    }
}