package com.example.jiangshan.mapper.domain;

import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import com.example.jiangshan.entity.DeviceChannel;
import org.springframework.stereotype.Repository;

@Repository
@Mapper
public interface DeviceChannelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_channel
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String channelId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_channel
     *
     * @mbg.generated
     */
    DeviceChannel selectByPrimaryKey(String channelId);

    void batchInsert(@Param("deviceChannels") List<DeviceChannel> deviceChannels);

    List<DeviceChannel> listChannelsBySerial(@Param("deviceSerial") String deviceSerial);

    DeviceChannel selectByChannel(@Param("deviceSerial") String deviceSerial, @Param("channelNo") Integer channelNo);
}