package com.example.jiangshan.mapper.domain;

import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import com.example.jiangshan.entity.Person;
import org.springframework.stereotype.Repository;

@Repository
@Mapper
public interface PersonMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table person
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table person
     *
     * @mbg.generated
     */
    int insertSelective(Person record);

    Person selectByEmployeeNo(@Param("employeeNo") String employeeNo);

    List<Person> listPersons();

    void batchInsert(@Param("persons") List<Person> persons);
}